export const GET_RATES_INIT = 'GET_RATES_INIT';
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';

export const CREATE_EXCHANGE_INIT = 'CREATE_EXCHANGE_INIT';
export const CREATE_EXCHANGE_SUCCESS = 'CREATE_EXCHANGE_SUCCESS';

export const COMPLETE_EXCHANGE_INIT = 'COMPLETE_EXCHANGE_INIT';
export const COMPLETE_EXCHANGE_SUCCESS = 'COMPLETE_EXCHANGE_SUCCESS';

export const CANCEL_EXCHANGE_INIT = 'CANCEL_EXCHANGE_INIT';
export const CANCEL_EXCHANGE_SUCCESS = 'CANCEL_EXCHANGE_SUCCESS';

export const PROCESS_CODE_INIT = 'PROCESS_CODE_INIT';
export const PROCESS_CODE_SUCCESS = 'PROCESS_CODE_SUCCESS';

export const VALIDATE_COUPON_INIT = 'VALIDATE_COUPON_INIT';
export const VALIDATE_COUPON_SUCCESS = 'VALIDATE_COUPON_SUCCESS';

export const DELETE_COUPON = 'DELETE_COUPON';

export const EXCHANGE_ERROR = 'EXCHANGE_ERROR';
