version: 0.2

phases: 
  install:
    commands: 
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - apt-get install gettext-base

  pre_build:
    run-as: root
    commands:
      - echo "Agent is ready"
      - aws --version
      - export KUBECONFIG=$HOME/.kube/config

  build:
    run-as: root
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 160743850946.dkr.ecr.us-east-2.amazonaws.com
      - cd $CODEBUILD_SRC_DIR
      - echo 'Building image...'
      - docker build -t 160743850946.dkr.ecr.us-east-2.amazonaws.com/frontend-client-repo:$ENVIRONMENT-$CODEBUILD_BUILD_NUMBER -t 160743850946.dkr.ecr.us-east-2.amazonaws.com/frontend-client-repo:$ENVIRONMENT-latest .
      - echo 'Pushing image into ECR...' 
      - docker push 160743850946.dkr.ecr.us-east-2.amazonaws.com/frontend-client-repo --all-tags
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/deploy/base
      - envsubst < deployment.template > deployment.yaml
      - cat deployment.yaml
      - aws eks update-kubeconfig --region us-east-2 --name $K8S_CLUSTER 
      - kubectl apply -f deployment.yaml -n app


