export const REFRESH_TOKEN_INIT = "REFRESH_TOKEN_INIT";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";

export const LOADUSER_INIT = "LOADUSER_INIT";
export const LOADUSER_SUCCESS = "LOADUSER_SUCCESS";

export const SIGNGIN_INIT = "SIGNGIN_INIT";
export const SIGNGIN_SUCCESS = "SIGNGIN_SUCCESS";

export const REFRESH_CODE_INIT = "REFRESH_CODE_INIT";
export const REFRESH_CODE_SUCCESS = "REFRESH_CODE_SUCCESS";

export const SIGNIN_GOOGLE = "SIGNIN_GOOGLE";

export const COMPLETE_PROFILE_INIT = "COMPLETE_PROLFIE_INIT";

export const SIGNGUP_INIT = "SIGNGUP_INIT";
export const SIGNGUP_SUCCESS = "SIGNGUP_SUCCESS";

export const LOGOUT_INIT = "LOGOUT_INIT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const RECOVER_PASSWORD_INIT = "RECOVER_PASSWORD_INIT";
export const RECOVER_PASSWORD_SUCCESS = "RECOVER_PASSWORD_SUCCESS";

export const RESET_PASSWORD_INIT = "RESET_PASSWORD_INIT";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

export const VALIDATE_EMAIL_INIT = "VALIDATE_EMAIL_INIT";
export const VALIDATE_EMAIL_SUCCESS = "VALIDATE_EMAIL_SUCCESS";

export const SET_USER_DATA = "auth/SET_USER_DATA";

export const AUTH_ERROR = "@auth/AUTH_ERROR";
export const GOOGLE_ERROR = "@auth/GOOGLE_ERROR";