export const GET_BANKS = "accounts/GET_BANKS";
export const GET_CURRENCIES = "accounts/GET_CURRENCIES";

export const GET_ACCOUNTS = {
  LOADING: "accounts/GET_ACCOUNTS_LOADING",
  SUCCESS: "accounts/GET_ACCOUNTS_SUCCESS",
};

export const GET_KASH_ACCOUNT = {
  LOADING: "accounts/GET_KASH_ACCOUNT_LOADING",
  SUCCESS: "accounts/GET_KASH_ACCOUNT_SUCCESS",
};

export const ADD_ACCOUNT_INIT = "ADD_ACCOUNT_INIT";
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";

export const SET_ACCOUNT_DETAILS_INIT = "SET_ACCOUNT_DETAILS_INIT";
export const SET_ACCOUNT_DETAILS_SUCCESS = "SET_ACCOUNT_DETAILS_SUCCESS";

export const EDIT_ACCOUNT_INIT = "EDIT_ACCOUNT_INIT";
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS";

export const DELETE_ACCOUNT_INIT = "DELETE_ACCOUNT_INIT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";

export const WITHDRAW_KASH_INIT = "WITHDRAW_KASH_INIT";
export const WITHDRAW_KASH_SUCCESS = "WITHDRAW_KASH_SUCCESS";

export const ACCOUNTS_ERROR = "ACCOUNTS_ERROR";
