export const GET_ACCOUNTS_INIT = 'GET_ACCOUNTS_INIT';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';

export const GET_KASH_ACCOUNT_INIT = 'GET_KASH_ACCOUNT_INIT';
export const GET_KASH_ACCOUNT_SUCCESS = 'GET_KASH_ACCOUNT_SUCCESS';

export const ADD_ACCOUNT_INIT = 'ADD_ACCOUNT_INIT';
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';

export const SET_ACCOUNT_DETAILS_INIT = 'SET_ACCOUNT_DETAILS_INIT';
export const SET_ACCOUNT_DETAILS_SUCCESS = 'SET_ACCOUNT_DETAILS_SUCCESS';

export const EDIT_ACCOUNT_INIT = 'EDIT_ACCOUNT_INIT';
export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT_SUCCESS';

export const DELETE_ACCOUNT_INIT = 'DELETE_ACCOUNT_INIT';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';

export const WITHDRAW_KASH_INIT = 'WITHDRAW_KASH_INIT';
export const WITHDRAW_KASH_SUCCESS = 'WITHDRAW_KASH_SUCCESS';

export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR';
