export const GET_PROFILES_INIT = 'GET_PROFILES_INIT';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';

export const ADD_PROFILE_INIT = 'ADD_PROFILE_INIT';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';

export const EDIT_USER_CODE_INIT = 'EDIT_USER_CODE_INIT';
export const EDIT_USER_CODE_SUCCESS = 'EDIT_USER_CODE_SUCCESS';

export const EDIT_PROFILE_INIT = 'EDIT_PROFILE_INIT';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';

export const UPLOAD_DOCUMENT_INIT = 'UPLOAD_DOCUMENT_INIT';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';

export const SELECT_PROFILE_INIT = 'SELECT_PROFILE_INIT';
export const SELECT_PROFILE_SUCCESS = 'SELECT_PROFILE_SUCCESS';

export const PROFILES_ERROR = 'PROFILES_ERROR';
