export const GET_PROFILES_INIT = "GET_PROFILES_INIT";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";

export const ADD_PROFILE_INIT = "ADD_PROFILE_INIT";
export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";

export const DISABLE_PROFILE_INIT = "DISABLE_PROFILE_INIT";
export const DISABLE_PROFILE_SUCCESS = "DISABLE_PROFILE_SUCCESS";

export const EDIT_USER_CODE_INIT = "EDIT_USER_CODE_INIT";
export const EDIT_USER_CODE_SUCCESS = "EDIT_USER_CODE_SUCCESS";

export const EDIT_BASIC_INFO_INIT = "profile/EDIT_BASIC_INFO_INIT";
export const EDIT_BASIC_INFO_SUCCESS = "profile/EDIT_BASIC_INFO_SUCCESS";

export const EDIT_ADDITIONAL_INFO_INIT = "profile/EDIT_ADDITIONAL_INFO_INIT";
export const EDIT_ADDITIONAL_INFO_SUCCESS = "profile/EDIT_ADDITIONAL_INFO_SUCCESS";

export const UPLOAD_DOCUMENT_INIT = "UPLOAD_DOCUMENT_INIT";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";

export const SELECT_PROFILE_INIT = "SELECT_PROFILE_INIT";
export const SELECT_PROFILE_SUCCESS = "SELECT_PROFILE_SUCCESS";

export const GET_USER_DATA_INIT = "GET_USER_DATA_INIT";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";

export const PROFILES_ERROR = "PROFILES_ERROR";
