export const GET_ORDERS_INIT = 'GET_ORDERS_INIT';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';

export const GET_WITHDRAWALS_INIT = 'GET_WITHDRAWALS_INIT';
export const GET_WITHDRAWALS_SUCCESS = 'GET_WITHDRAWALS_SUCCESS';

export const GET_ORDER_DETAILS_INIT = 'GET_ORDER_DETAILS_INIT';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';

export const GET_ORDER_AMOUNTS_INIT = 'GET_ORDER_AMOUNTS_INIT';
export const GET_ORDER_AMOUNTS_SUCCESS = 'GET_ORDER_AMOUNTS_SUCCESS';

export const GET_TOTAL_AMOUNT_INIT = 'GET_TOTAL_AMOUNT_INIT';
export const GET_TOTAL_AMOUNT_SUCCESS = 'GET_TOTAL_AMOUNT_SUCCESS';

export const ACTIVITY_ERROR = 'ACTIVITY_ERROR';
