name: developCI

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.TEST_GOOGLE_CLIENT_ID }}
      REACT_APP_FB_PIXEL_ID: ${{ secrets.FB_PIXEL_ID }}
      REACT_APP_AUTH_API: ${{ secrets.TEST_AUTH_API }}
      REACT_APP_ACCOUNTS_API: ${{ secrets.TEST_ACCOUNTS_API }}
      REACT_APP_EXCHANGE_API: ${{ secrets.TEST_EXCHANGE_API }}
      AWS_CF_DISTRIBUTION_ID: EU6IRE21LXH82
      AWS_REGION: us-east-2
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build de application
        run: yarn build
