name: Instakash-client CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      REACT_APP_FB_PIXEL_ID: ${{ secrets.FB_PIXEL_ID }}
      REACT_APP_AUTH_API: ${{ secrets.AUTH_API }}
      REACT_APP_ACCOUNTS_API: ${{ secrets.ACCOUNTS_API }}
      REACT_APP_EXCHANGE_API: ${{ secrets.EXCHANGE_API }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
      - run: yarn install
      - run: yarn build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2" # optional: defaults to us-east-1
          SOURCE_DIR: "build" # optional: defaults to entire repository
