name: Instakash-client CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v1
        with:
          cmd: install
        widh:
          cmd: build
